# Generated by Django 5.1.7 on 2025-03-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_medicinereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineReview',
        ),
    ]
